### PR TITLE
Update SEIV token info

### PR DESCRIPTION
**Pull request by Ikeh-Akinyemi**

### CODE REVIEW

**Review by afsardo — CHANGES_REQUESTED** [review]
There is already an existing token with exact same info, please either use a different logo, or different symbol, otherwise it is confusing for users.

**Comment by Ikeh-Akinyemi** [comment]
> There is already an existing token with exact same info, please either use a different logo, or different symbol, otherwise it is confusing for users.

We deployed the existing token, but want to revamp by deploying a new one. How do I use a different logo if the name of the image file should match the symbol of the token, and that already exists?

**Comment by afsardo** [comment]
Well, it is misleading to users, that they see 2 tokens exactly the same, they have no idea which one is what.

**Comment by afsardo** [comment]
You can use any logo image filename no problem.

**Comment by Ikeh-Akinyemi** [comment]
> You can use any logo image filename no problem.

We have removed liquidity for the first token, and if there's a way to take it down, please do let me know. So now, I have uploaded a new logo, and we want to keep the name as it represent the narrative/brand that the project is all about.

Please what exactly is holding the PR from being merged now? I have added a new entry for the token, added a fresh new token with a different logo for the new entry, so what is holding the PR now? Please do let me know. It will be helpful to be quite explicit about what you want me to do, as I believe I have done all you requested of.

**Pull request merged**
