### PR TITLE
Update Logo Size used for GEM 

### PR DESCRIPTION
**Pull request by Studio-Mojo**
Just an size update to GEM Logo to make it match the icon used in the rest of the cosmos. 

Thank you!

### CODE REVIEW

**Comment by afsardo** [comment]
@Studio-Mojo can you fix the PR? It's also adding a new image outside the img folder.

**Review by afsardo — CHANGES_REQUESTED** [review]
@Studio-Mojo can you fix the PR? It's also adding a new image outside the img folder.

**Comment by Studio-Mojo** [comment]
> @Studio-Mojo can you fix the PR? It's also adding a new image outside the img folder.

@afsardo > I apologize for the image in the wrong place, I am not a DEV but was getting guidance from others to work on updating the GEM Icon. It's clear I didn't do something correctly and the community passed the below proposal, since the last Image hosting location was creating 404 errors. 

So I don't know how to fix it promptly and fear messing things up more - if you or someone else knows the needed coding, please advise. 

----

Per GEM DAO Passed Prop the community has secured a location for the GEM LOGO.

Here is the passed proposal and if someone can help see this update through > thank you!
https://dao.enterprise.money/dao/proposal?address=terra1f43s2vecnmlany8q87e6qafj6mnu249k0yqzg477qsdhzsv39dhq5kxdsj&id=65

Here is the Icon link in the proposal: https://bafkreigfw66cljelcuurfbwx3ccrp7cpwuga6boygmo22xr74oaady4dxq.kirud.link/

**Comment by Studio-Mojo** [comment]
Mahalo for the help!  Have a blessed week ahead!

**Pull request merged**
