### PR TITLE
Update sei.json

### PR DESCRIPTION
**Pull request by anhdt3107**

### CODE REVIEW

**Comment by anhdt310720** [comment]
it's good now, pls check it

**Review by anhdt310720 — CHANGES_REQUESTED** [review]
it's good now, pls check it

**Comment by afsardo** [comment]
It's missing the image.

**Comment by anhdt3107** [comment]
I commit img before

**Review by afsardo — CHANGES_REQUESTED** [review]
It's missing the image.

**Comment by anhdt3107** [comment]
ok I commit img again

**Pull request closed without merging**
