### PR TITLE
Update neutron.json (incorrect ibc/denom)

### PR DESCRIPTION
**Pull request by SmolFatality**
So the previous ibc/denom was the token being ibcd from chihuahua chain to osmosis and then to astroport. This ibc/denom is just from chihuahua chain to astroport. Thanks for the review.

### CODE REVIEW

**Review by afsardo — APPROVED** [review]

**Comment by afsardo** [comment]
@SmolFatality can you leave the old info but add `(Osmosis)` to the symbol?

**Comment by SmolFatality** [comment]
I'll do it now.

**Comment by SmolFatality** [comment]
So should I add a whole other token with just the normal from Chihuahua?

**Comment by afsardo** [comment]
Yes exactly

**Comment by afsardo** [comment]
@SmolFatality add the (Osmosis) at the end.

**Comment by SmolFatality** [comment]
Done, let me know if you need anything else. Thanks!

**Review by afsardo — APPROVED** [review]

**Pull request merged**
