### PR TITLE
Add SEITAMA token

### PR DESCRIPTION
**Pull request by Setiamaon**
SEITAMA
website- https://seitama.xyz/

### CODE REVIEW

**Comment by afsardo** [comment]
Missing image?

**Review by afsardo — CHANGES_REQUESTED** [review]
Missing image?

**Comment by Setiamaon** [comment]
> Missing image?

ok, i think i just added it. LMK if that was what you needed.

**Comment by afsardo** [comment]
Not seeing the commit in the PR

**Pull request closed without merging**
