### PR TITLE
Remove GDD

### PR DESCRIPTION
**Pull request by 0xIkalgo**
This token rugged. Confusing and don't think it should be up in an official registry

### CODE REVIEW

**Comment by goddardneutron** [comment]
Don't think a newly created github account is asking for the deletion of a token that still has liquidity.

If you own Goddard plagiarism on Astroport, you should learn about free financial markets.

**Comment by 0xIkalgo** [comment]
Don't understand the complaint.
1. Not an old account, been in the crypto development space.
2. This repository seems to be a registry of verified assets. Free financial markets is separate from that.
3. Still having liquidity doesn't mean the token did not rug.
 
In any case, this repo belongs to Astroport, and they are the final arbiter of what gets shown on their platform. I don't really care what decision they make, but I don't believe it's okay to show an asset as supported which clearly dumped from a large early holder, has a community which lost money on it, and 0 activity/response.

If they want to close this, that's fine by me.

image

**Comment by 0xIkalgo** [comment]
image
image

**Comment by afsardo** [comment]
This is not any list of verified assets, its simple a repo of metadata, there are multiple tokens that rugged unfortunatly, but we dont make any judgements whatsoever, I'm sorry to hear about this :X

**Pull request closed without merging**
